format_version: 10
pipelines:
  build-application:
    group: CatApplication
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c240b63:
        git: https://github.com/mewchildy/TestApplication.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - build:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            resources:
            - dev
            tabs:
              cat: cat-app.html
            artifacts:
            - build:
                source: cat-app.html
                destination: ''
            tasks:
            - exec:
                command: make
                arguments:
                - install-cat-application
                run_if: passed         