apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "cat-application.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    app.kubernetes.io/name: {{ include "cat-application.fullname" . }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: Prefix
        backend:
          serviceName: {{ .Values.ingress.backendName }}
          servicePort: {{ .Values.ingress.backendPort }}
