# Default values for cat-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: "janesee3/cat-application"
  tag: "1"

service:
  type: ClusterIP
  port: 80

ingress:
  class: "nginx"
  host: "a0b496b7343764e56a2dc93f215686cd-1474765926.us-east-2.elb.amazonaws.com"
  path: "/cats"
  backendName: "cat-application"
  backendPort: 80

containerPortName: cat-port