apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "meow-application.fullname" . }}
  labels:
{{ include "meow-application.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "meow-application.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "meow-application.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.env }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          ports:
            - name: {{ .Values.containerPortName }}
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /meow
              port: {{ .Values.containerPortName }}